version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./pos-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:4000
    command: ["vite", "--host"]
    volumes:
      - ./pos-frontend:/app 

  api:
    depends_on:
      - db
    build: ./pos-backend
    ports:
      - "4000:4000"
    environment:
      DB_URL: mongodb+srv://azamatielts987:pERharMAr7osuOls@nodedata.zwv2x.mongodb.net/POS-management?retryWrites=true&w=majority&appName=NodeData
    volumes:
      - ./pos-backend:/app 

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - anime:/data/db

volumes:
  anime:
